import Breadcrumb from './Breadcrumb';

export type { BreadcrumbProps } from './Breadcrumb';
export type { BreadcrumbItemProps } from './BreadcrumbItem';

console.log('BreadcrumbItemPropsBreadcrumbItemPropsBreadcrumbItemPropsBreadcrumbItemPropsBreadcrumbItemPropsBreadcrumbItemPropsBreadcrumbItemPropsBreadcrumbItemPropsBreadcrumbItemPropsBreadcrumbItemPropsBreadcrumbItemPropsBreadcrumbItemPropsBreadcrumbItemPropsBreadcrumbItemPropsBreadcrumbItemPropsBreadcrumbItemPropsBreadcrumbItemPropsBreadcrumbItemPropsBreadcrumbItemPropsBreadcrumbItemPropsBreadcrumbItemPropsBreadcrumbItemPropsBreadcrumbItemPropsBreadcrumbItemPropsBreadcrumbItemPropsBreadcrumbItemPropsBreadcrumbItemProps')

export default Breadcrumb;
