on: [pull_request]

name: ChatGPT CodeReview

jobs:
  chatgpt_comment:
    runs-on: ubuntu-latest
    name: Let chatgpt comment on your PR.
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: ChatGPT comment
        uses: afc163/chatgpt-action@main
        id: chatgpt
        with:
          number: ${{ github.event.pull_request.number }}
          apiKey: ${{ secrets.CHATGPT_API_KEY }}
          split: 'yolo'  # Use true to enable the unstable split feature.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
