name: 📦 Size Limit

on:
  pull_request:
    types: [opened, synchronize]

# Cancel prev CI if new commit come
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  size:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1

    steps:
    - uses: actions/checkout@v3
    - uses: ant-design/size-limit-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        script: npx size-limit --json --why
